apiVersion: apps/v1
kind: Deployment
metadata:
  name: myParcel
  labels:
    app: myParcel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myParcel
  template:
    metadata:
      labels:
        app: myParcel
    spec:
      containers:
        - name: myParcel
          image: username/myParcel:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5